### ISSUE TITLE
Function toggle all does not work in Internet Explorer

### ISSUE THREAD

**Issue by Kiki-Jiki** [gimli2/sigal#14]
The JS syntax used in _toggleAllCheckboxes()_ function is probably not supported in Internet Explorer. I'm using IE11, trying to emulate older versions using browser's Developer tool has no affect. Replacing the for-in cycle with common for cycle in _toggleAllCheckboxes()_ function seems to make it work.

``` javascript
for (var i = 0; i < elems.length; i++) {...
```

**Comment by gimli2** [comment]
Fixed in commit 377d6000390361c94bfa382a066ccb1f112d22e6 in branch lang.
